server:
  port: 9000
  address: 0.0.0.0
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
  jackson:
    defaultPropertyInclusion: non_null
    deserialization:
      fail_on_unknown_properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.175.35:3306/adastra?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: adastra
    password: mlb20000102
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
#    password: 123
    database: 0
    timeout: 1800000
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 60s
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 1
  mail:
    host: smtp.qq.com
    username: 2762404119@qq.com
    password: wopenrzwqnfhdhdh
    default-encoding: utf-8
    port: 465
    properties:
      mail.smtp.ssl.enable: true
    protocol: smtps
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
sms:
  app:
    id: 1400683116
    key: 95f32e5cdb35bbc88dbcedb41b6934e4
    template:
      universal: 1419186
    sign: isamumu
  size: 6

aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyId: LTAI5tJTSkD8cSxk1dazEqLV
      keysecret: 0iN9FRV610rfHP5bfzKVuZxIcCdlc5
      bucketname: libilibi-host

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.am.adastra.entity
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      am:
        adastra: warn
knife4j:
  enable: true

alipay:
  #支付宝开放平台生成的APP的ID
  appId: 2021000120697558
  #私钥
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC73r8oUJ2h6RubamysWlNjnLAhGWDiflbOL/1ChA5mLNY3xUHeSp6SmVsyk1pR1hV6xh4sb+uc/QVjcUwb/ojn5LyjpQajhojPjK8u83avZT6/u+2+SWJhkHZshzERyJJ5W5t9ZqFL5RkqUSYmu4auuWYHJFz70Utk5nbDX9kplDePISlBxftaoOBU1/W9e4Fby+Z/gQSZSicG1AVCgpYM5AOkajTa1d2QQMv9LseaUyGVwBnCIFtg03iNTDu2mqIVsvcAm/awsEg75Yj5mNYxuJVEkfeUCjTm8SPdbJsHqSSrN0q28r4ZKdCv3puInsoDqYilw7cLgKCEKwP5ZuDdAgMBAAECggEBAJ/PBsSAbtZ/uGAn03F5FF4ztw8wy11fIvAZmlGui6EWmtKuFS3GQ8Vodk87USUz+umJBbm/KqlMAf1pLtjRWBwKUvzRMCiCFHaYsZw6tcbVVN88OSwYuHtNq67+ARujhhV9e3LcjnBE3XdFuDJSamrOgp+oqv/6NSwLbxMawVu/o4ReZVzVi3MKvjXjbA01YxZy3X0T2IE+qSw8L0pCp6KDv0b5MFIMngqmVU+YRup2tpGaTsh2y2ksfgy5hyCy/amj3gd2pgrSOJyPgyDmi7uYjjN0eyda6cEoMMIsHch8JIETXMApE4fISplfgdljZGx3PmnmgN/J35FmixcdZQECgYEA/swaJsumPUCRW4RlkwyXmTeWTxIYdp421uQzA7K/J75r6IxmCKXM5Jsf1zrb65rG/1q3SZ9NM16glm2BN/OZMdFHYAi8+JV+ijm4ODTVOTm+5P0daKH7sS2PiNd3fWssPh0SsrbIUHnyaHcgRtQbSjj6sz+nfI2hyBZk1IkwPfECgYEAvMHFAQzzo4nXKKzzndDc7OsAUtJfi/3x2mYpx3g0yrGt+Ne5kEgUKI2ocP5voY5MhPDXLg8lIojzF/AcVQgUT3VdbeGbARyk6h3W1rDFifdGqYT+0tFCeTxIoldmGYfepwzZPQGEQD+Eneeee9Nd6L/PdgG0XGhUhCPCH6b8Va0CgYEArlWmOw8yMkzAaBbBjQibnWjsPjPKaza7nPLMeOZPZnkiyh1uHtKay3vcIF6UZLMlH0jJieUmZFSFmgdY15ikI/LmXC3+ZjObPiZaBpMXpSz+kR0ihxn15Xef8uhCSJ0Qy3sG9SKdEnstwg5oFi5AcdtkpUqTZWRe4lF4Mfef+3ECgYAPSyvpH+GFuJ9kPk8m1EtyLsBB9aWkNBkqduifrs+oNKlB5ki0tgJcHs4tCZCF6H+urczhgHyjxbDcmanSAeuTXJELXCIw/t8l0PEdSAlZWl2xUoNLFYVrSUUhUi+FlgqmQlY/qSXMBtl56dBffAq51wC6MP0qF5Hxeuw5oFAFqQKBgQCx5CWz2VeUn8QuM6FEPhNDsdtHHEXEkRGE1kKeXoQQqQYRdQynqNyp5fOMvoFgBQbtxCJo8fNN6PJ6NHnTn1gTO9sakCa5U+fQQVqcHFX2B3wZhUT5fumfavXrPuk5EY0ydp6y8HKO97zulxA8EpNOl3naPPc1I294+61PQO9Nlg==
  #公钥
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu96/KFCdoekbm2psrFpTY5ywIRlg4n5Wzi/9QoQOZizWN8VB3kqekplbMpNaUdYVesYeLG/rnP0FY3FMG/6I5+S8o6UGo4aIz4yvLvN2r2U+v7vtvkliYZB2bIcxEciSeVubfWahS+UZKlEmJruGrrlmByRc+9FLZOZ2w1/ZKZQ3jyEpQcX7WqDgVNf1vXuBW8vmf4EEmUonBtQFQoKWDOQDpGo02tXdkEDL/S7HmlMhlcAZwiBbYNN4jUw7tpqiFbL3AJv2sLBIO+WI+ZjWMbiVRJH3lAo05vEj3WybB6kkqzdKtvK+GSnQr96biJ7KA6mIpcO3C4CghCsD+Wbg3QIDAQAB
  #支付网关配置，这一项是写死的，正式环境是openapi.alipay.com
  gateway: openapi.alipaydev.com
  #支付成功之后的回调页面，只是一个友好页面。主要换成你自己映射的临时域名
  returnUrl:
  #支付成功的接口回调，我们还没写，先空着
  notifyUrl: http://localhost:8080/UserVip/notify

