server:
  port: 9000
  address: 0.0.0.0

spring:
  redis:
    host: 10.1.188.46
    port: 6379
    database: 0
    password: password
    timeout: 60s

    lettuce:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1s
        max-active: -1

  jackson:
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.175.35:3306/adastra?characterEncoding=utf-8&serverTimezone=UTC
    username: adastra
    password: mlb20000102
    type: com.alibaba.druid.pool.DruidDataSource
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id:

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.am.adastra.entity



