server:
  port: 8160
  address: 0.0.0.0
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
  jackson:
    defaultPropertyInclusion: non_null
    deserialization:
      fail_on_unknown_properties: false
  datasource:
    #    url: jdbc:mysql://175.24.175.35:3306/adastra?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #    username: teacher
    #    password: teacher
    url: jdbc:mysql://10.1.188.121:3306/adastra?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootmlb
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 1800000
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 60s
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 1
  mail:
    host: smtp.qq.com
    username: 2762404119@qq.com
    password: wopenrzwqnfhdhdh
    default-encoding: utf-8
    port: 465
    properties:
      mail.smtp.ssl.enable: true
    protocol: smtps
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
sms:
  app:
    id: 1400683116
    key: 95f32e5cdb35bbc88dbcedb41b6934e4
    template:
      universal: 1419186
    sign: isamumu
  size: 6
alipay:
  #  call_back: http://adastra.isamumu.cn:8160/pay/callback
  #  call_back: http://localhost:8160/pay/callback
  call_back: http://10.1.188.121:8160/pay/callback
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyId: LTAI5tJTSkD8cSxk1dazEqLV
      keysecret: 0iN9FRV610rfHP5bfzKVuZxIcCdlc5
      bucketname: libilibi-host

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.am.adastra.entity
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      am:
        adastra: warn
knife4j:
  enable: true

wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    #    redirect_url: http://adastra.isamumu.cn:8160/api/ucenter/wx/callback
    #    redirect_url: http://localhost:8160/api/ucenter/wx/callback
    redirect_url: http://10.1.188.121:8160/api/ucenter/wx/callback


