server:
  port: 9000
  address: 0.0.0.0

spring:
  jackson:
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.175.35:3306/adastra?characterEncoding=utf-8&serverTimezone=UTC
    username: adastra
    password: mlb20000102
    type: com.alibaba.druid.pool.DruidDataSource
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id:
  mail:
    host: smtp.qq.com
    username: 2762404119@qq.com
    password: wopenrzwqnfhdhdh
    default-encoding: utf-8
    port: 465
    properties:
      mail.smtp.ssl.enable: true
    protocol: smtps

sms:
  app:
    id: 1400683116
    key: 95f32e5cdb35bbc88dbcedb41b6934e4
    template:
      universal: 1419186
    sign: isamumu
  size: 6

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.am.adastra.entity

logging:
  level:
    com:
      am:
        adastra:
          info



