spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.175.35:3306/libilibi?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 20000102@Mlb

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.am.libilibi.entity

server:
  port: 9000
  address: 0.0.0.0

